name: Deploy App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      profile: ${{ steps.set-profile.outputs.profile }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Set Spring profile by branch
        id: set-profile
        run: |
          echo "PROFILE=prod" >> $GITHUB_ENV
          echo "profile=prod" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: |
          cd /home/runner/work/kiosk-be/kiosk-be
          ./gradlew clean bootjar -Pprofile=${PROFILE}

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build
        run: |
          cd /home/runner/work/kiosk-be/kiosk-be/docker
          docker buildx build -f ./docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} --push .
          

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy on server
        env:
          PROFILE: ${{ needs.build.outputs.profile }}
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
          cd /home/ubuntu/actions-runner/_work/kiosk-be/kiosk-be/docker
          echo "$ENV_PROD" > ./.env
          echo "PROFILE=prod" >> ./.env
          docker compose -f docker-compose.yml --env-file ./.env down
          docker compose -f docker-compose.yml --env-file ./.env pull
          docker compose -f docker-compose.yml --env-file ./.env up -d --build