name: Deploy Monitoring

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cd-monitoring.yml'
      - 'docker/docker-compose-monitoring.yml'
      - 'docker/grafana/'
      - 'docker/prometheus/'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.GIT_ACTION_TOKEN }}'

      - name: Deploy Monitoring
        run: |
          cd /home/ubuntu/actions-runner/_work/kiosk-be/kiosk-be/docker
          docker compose -f docker-compose-monitoring.yml down
          docker compose -f docker-compose-monitoring.yml pull
          docker compose -f docker-compose-monitoring.yml up -d --build
        
      
